[mypy]
python_version = 3.13
strict = True
check_untyped_defs = True
strict_optional = True
no_implicit_optional = True
warn_unreachable = True
warn_redundant_casts = True
warn_unused_ignores = True

[mypy-pytest.*]
ignore_missing_imports = True
