"""A merge regenerates the documents it invalidated, because a unit cannot know which they are.

THE FAILURE, measured 30 August 2026. Unit work added four lines to src/consilient/upstream.py.
`docs/diagrams/module-dependency.mmd` records a SHA-256 of its source, so the hash moved and
tests/test_build_diagrams.py failed. `suite_green()` went false, and suite_green gates BOTH
retirement and publication -- so the entire pipeline stopped for ten hours. Nothing published
between 02:12 and 12:05, and `done` sat at 13 all morning.

The diagram's CONTENT had not changed. The diff was one provenance header line; no dependency
edge moved.

A unit cannot reasonably be expected to know that editing a source file invalidates an artefact
it never opened, and working principle 4 says the fix goes in code rather than in a brief. So the
driver regenerates on the unit's behalf, after the unit's commits apply and before the gate runs
-- the only point at which the tree the gate sees is the tree the merge produced.
"""

from __future__ import annotations

import json
from pathlib import Path

from tests.build_driver_helpers import ROOT, _load_driver

DRIVER = _load_driver()
MANIFEST = ROOT / "docs" / "generated-manifest.json"


def test_every_manifest_producer_is_run() -> None:
    """The registry is the repository's own; duplicating it here would create a second truth."""
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))["entries"]
    expected = {entry["producer"] for entry in entries}
    actual = {cmd[-1] for cmd in DRIVER.generated_document_producers()}
    missing = expected - actual
    assert not missing, f"manifest producers not run by the driver: {sorted(missing)}"


def test_the_diagrams_and_counts_are_run_although_absent_from_the_manifest() -> None:
    """Their absence from the registry is the specific gap that stopped the pipeline.

    If either is ever added to generated-manifest.json this test still passes, because it asserts
    the command runs rather than where its name came from.
    """
    actual = {cmd[-1] for cmd in DRIVER.generated_document_producers()}
    for producer in ("scripts/build_diagrams.py", "scripts/build_counts.py"):
        assert producer in actual, (
            f"{producer} is not regenerated by the driver. It is not in "
            "generated-manifest.json either, so nothing would regenerate it and a unit "
            "touching src/ stops the whole build."
        )


def test_every_producer_named_actually_exists() -> None:
    """A command that cannot run leaves the drift in place and the gate fails as before."""
    for cmd in DRIVER.generated_document_producers():
        assert (ROOT / cmd[-1]).is_file(), f"{cmd[-1]} does not exist"


def test_regeneration_happens_before_the_gate_not_after() -> None:
    """Order is the whole point: regenerating after the gate repairs a tree already refused.

    Asserted on the source because driving a real merge needs a unit worktree, a plan entry, a
    claim and a clean main tree -- that would test the fixture rather than the ordering. The
    ordering is what changed and what can silently regress.
    """
    source = Path(DRIVER.__file__ or "").read_text(encoding="utf-8")
    regen_at = source.find("regenerate_generated_documents(uid)")
    gate_at = source.find("gate_fail = gate_merged_tree(")
    assert regen_at != -1, "the merge path no longer regenerates generated documents"
    assert gate_at != -1, "the merge gate call has moved; re-read this test"
    assert regen_at < gate_at, (
        "regeneration now runs AFTER the merge gate, so the gate still sees the stale "
        "artefacts and the pipeline stops exactly as it did on 30 August 2026"
    )


def test_the_regeneration_commit_is_attributed_to_the_driver() -> None:
    """The trail must say who regenerated what, rather than folding it into the unit's work."""
    source = Path(DRIVER.__file__ or "").read_text(encoding="utf-8")
    body = source.partition("def regenerate_generated_documents")[2].partition(
        "\ndef "
    )[0]
    assert "--signoff" in body, (
        "the regeneration commit carries no sign-off; DCO requires one on everything reaching main"
    )
    assert "invalidated by" in body, (
        "the commit message no longer names the unit whose merge invalidated the documents"
    )


def test_a_regeneration_commit_does_not_block_the_rollback() -> None:
    """The rollback must be free to discard the driver's OWN regeneration commit.

    MEASURED 30 August 2026. `merge_unit_worktree` refuses to roll back when HEAD has moved
    past its last cherry-pick, a guard added on 25 August after a rollback destroyed a
    bystander's commit. The regeneration commit introduced above moves HEAD too -- but it is
    this merge's own work, not a bystander's. Until the mark advanced with it, every gate
    failure that followed a regeneration refused to roll back and left the failed merge
    applied: S02's monolith landed unvetted, orphaning four sibling modules and costing the
    suite 5 modules to collection errors.

    Asserted on the source for the same reason as the ordering check above: driving a real
    merge needs a unit worktree, a plan entry, a claim and a clean main tree, which would
    test the fixture rather than the invariant.
    """
    source = Path(DRIVER.__file__ or "").read_text(encoding="utf-8")
    regen_at = source.find("regenerate_generated_documents(uid)")
    gate_at = source.find("gate_fail = gate_merged_tree(")
    assert regen_at != -1, "the merge path no longer regenerates generated documents"
    assert gate_at != -1, "the merge gate call has moved; re-read this test"
    assert "post_pick_sha = " in source[regen_at:gate_at], (
        "a regeneration commit no longer advances post_pick_sha, so the bystander guard "
        "treats it as another writer and refuses to roll back a failed merge -- which is "
        "how a red tree was published-blocked and two units escalated on 30 August 2026"
    )
