"""What a dispatch turns out to have been, and the trajectory events that say so.

Three kinds are written here and nowhere else — dispatch.refused, dispatch.outcome and
dispatch.fanout — and their constants sit beside the functions that append them so that
one writer per kind stays visible rather than asserted. Appends go through
events.append, which remains the single writer of the authoritative log; this module
composes payloads, it does not open files.

Classification comes first because the classification is the finding. An exit code is
not an outcome: `classify_artefact` treats a zero exit with no output and a
workspace-trust marker as silent rather than ok, and `classify_gap` separates a
capability the harness does not have from one it merely failed at this time. Recording
the second as the first would put a false capability gap into the evidence base, which
is the error this project exists to measure.

capability.gap is appended here too, through the same single writer, and the kind is
imported from events.py rather than restated.
"""

import hashlib
from collections.abc import Sequence
from datetime import datetime, timezone
from pathlib import Path
from .events import (
    CAPABILITY_GAP_KIND,
    SCHEMA_VERSION,
    EventPayload,
    append,
)
from .harness_registry import (
    DISPATCH_ACTOR,
    Harness,
    SILENT_MARKERS,
    Status,
    VerdictKind,
)


__all__ = [
    "DISPATCH_ACTOR",
    "DISPATCH_OUTCOME_KIND",
    "FANOUT_KIND",
    "Harness",
    "REFUSED_KIND",
    "SILENT_MARKERS",
    "Status",
    "VerdictKind",
    "classify_artefact",
    "classify_gap",
    "judge_fanout",
    "make_run_id",
    "now_ts",
    "parse_status",
    "record_fanout",
    "record_gap",
    "record_outcome",
    "record_refusal",
]

REFUSED_KIND = "dispatch.refused"

DISPATCH_OUTCOME_KIND = "dispatch.outcome"

FANOUT_KIND = "dispatch.fanout"


def parse_status(value: str) -> Status:
    mapping: dict[str, Status] = {
        "ok": "ok",
        "silent": "silent",
        "failed": "failed",
        "timeout": "timeout",
        "refused": "refused",
        "killed": "killed",
    }
    try:
        return mapping[value]
    except KeyError as exc:
        raise ValueError(f"unknown dispatch status {value!r}") from exc


def classify_artefact(
    *,
    exit_code: int | None,
    stdout: str,
    stderr: str,
    output_bytes: int,
    diff_bytes: int,
    timed_out: bool,
) -> tuple[Status, str]:
    """Verify by artefact, never by exit code. Empty exit-0 is `silent`."""
    combined = f"{stdout}\n{stderr}"
    lowered = combined.casefold()
    # A trust banner with nothing else is silent (Cursor, measured). The same
    # banner buried in a 700 kB Codex transcript is not: twice on 21 Aug 2026
    # Codex wrote the named artefact and was recorded silent because agents.md
    # in the dump contained the marker. Marker wins only when there is no work.
    trust_only = output_bytes <= 200 and diff_bytes == 0
    for marker in SILENT_MARKERS:
        if marker in lowered and trust_only:
            return (
                "silent",
                f"harness produced no work: {marker!r} (exit {exit_code})",
            )
    if timed_out:
        return "timeout", f"timed out (exit {exit_code})"
    produced = (
        output_bytes > 0 or diff_bytes > 0 or bool(stdout.strip() or stderr.strip())
    )
    if not produced:
        return (
            "silent",
            f"exit {exit_code} with empty transcript and no diff",
        )
    if exit_code is None:
        return "failed", "process exited without a code"
    if exit_code != 0:
        return "failed", f"exit {exit_code}"
    return "ok", "produced an artefact"


def judge_fanout(
    first_text: str, second_text: str, first_ok: bool, second_ok: bool
) -> VerdictKind:
    if not first_ok or not second_ok:
        return "incomparable"
    left = " ".join(first_text.split()).casefold()
    right = " ".join(second_text.split()).casefold()
    if not left or not right:
        return "incomparable"
    if left == right:
        return "agree"
    return "disagree"


# Refusal-reason markers generated by this package and by scripts/dispatch.py. Each is
# pinned by a test, so a reworded reason breaks a test loudly rather than misclassifying
# a gap quietly. Matching prose this codebase writes is not parsing model output.
_GAP_NOT_IMPLEMENTED_MARKERS: tuple[str, ...] = (
    "not installed",
    "not on path",
    "not reachable",
    "no invocation for harness",
    "unknown harness",
    "no models registered",
    "no eligible model",
)

# Refusals that time closes on its own: quota windows reset and live claims expire.
# Every other refusal escalates — fail closed rather than guess at a self-repair. The
# aggregate selection refusal ("every pool is exhausted, unknown, or not installed")
# contains a not-implemented marker by construction, so it escalates: from prose alone
# the record cannot tell a resettable window from a missing install, and guessing is
# the failure this event exists to record.
_GAP_RETRY_MARKERS: tuple[str, ...] = (
    "exhausted",
    "claims overlap a live dispatch",
)


def classify_gap(status: str, reason: str) -> tuple[str, str, str] | None:
    """Map an existing dispatch signal to (failure, closure, repair), or None if no gap.

    This is the self-healing boundary stated as policy rather than prose. The system
    MAY close a gap itself only where another attempt is honest: a pool window
    resetting, a live claim expiring, or a loud failure worth one recorded re-attempt
    (closure "retry" — every re-attempt is itself recorded, so a retry that does not
    close the gap ranks it higher on the gap view). It MUST escalate a silent run (the
    measured laundering path: four exit-0 dispatches wrote nothing on 21 Aug 2026), a
    capability that is not implemented (no retry builds it), and every refusal this
    rule does not recognise. The record is the deliverable; an honest escalation beats
    a quiet failure to self-heal.
    """
    if status == "ok":
        return None
    if status == "silent":
        return (
            "silent",
            "escalate",
            "a human inspects why the harness reported success and produced nothing; "
            "dispatch policy already forbids an unattended retry on another pool",
        )
    if status in ("failed", "timeout", "killed"):
        return (
            "failed",
            "retry",
            "re-dispatch the task; if the same failure repeats it ranks higher on the "
            "capability-gap view and a human builds the fix",
        )
    lowered = reason.casefold()
    if any(marker in lowered for marker in _GAP_NOT_IMPLEMENTED_MARKERS):
        return (
            "not_implemented",
            "escalate",
            "install or build the named capability; no retry creates it",
        )
    if any(marker in lowered for marker in _GAP_RETRY_MARKERS):
        return (
            "refused",
            "retry",
            "re-dispatch once the pool window has reset or the live claim has expired",
        )
    return (
        "refused",
        "escalate",
        "a human changes what was asked, what is configured, or the policy that "
        "refused it",
    )


def record_gap(
    log_dir: Path,
    *,
    ts: str,
    run_id: str,
    task: str,
    cwd: str,
    attempted: str,
    failure: str,
    detail: str,
    closure: str,
    repair: str,
    source: str,
) -> EventPayload:
    """Append one capability.gap through the single writer (V0-41).

    `asked` is the task verbatim — the unprompted demand, expressed at the moment of
    need, which is the highest-signal thing a user produces. It stays inside the
    gitignored local trajectory under the same ADR-0057 rule as every dispatch record.
    """
    return append(
        log_dir / f"{ts[:10]}.jsonl",
        {
            "v": SCHEMA_VERSION,
            "ts": ts,
            "event": CAPABILITY_GAP_KIND,
            "actor": DISPATCH_ACTOR,
            "data": {
                "asked": task,
                "attempted": attempted,
                "failure": failure,
                "detail": detail,
                "closure": closure,
                "repair": repair,
                "run_id": run_id,
                "source": source,
            },
        },
    )


def now_ts() -> str:
    return datetime.now(timezone.utc).isoformat()


def make_run_id(ts: str, task: str, label: str) -> str:
    stamp = ts.replace("-", "").replace(":", "").replace("+", "Z")[:15]
    digest = hashlib.sha256(f"{ts}\n{label}\n{task}".encode()).hexdigest()[:10]
    return f"{stamp}-{digest}"


def _event(kind: str, ts: str, data: dict[str, object]) -> EventPayload:
    payload = dict(data)
    payload.setdefault("supervised", True)
    return {
        "v": SCHEMA_VERSION,
        "ts": ts,
        "event": kind,
        "actor": DISPATCH_ACTOR,
        "data": payload,
    }


def record_refusal(
    log_dir: Path,
    *,
    ts: str,
    run_id: str,
    task: str,
    cwd: str,
    reason: str,
    considered: Sequence[str],
    attempted: str = "harness selection",
) -> EventPayload:
    recorded = append(
        log_dir / f"{ts[:10]}.jsonl",
        _event(
            REFUSED_KIND,
            ts,
            {
                "run_id": run_id,
                "task": task,
                "cwd": cwd,
                "status": "refused",
                "reason": reason,
                "considered": list(considered),
            },
        ),
    )
    # A refusal is a capability gap the boundary already detected: the user asked, and
    # nothing ran. It is recorded as such here, at the chokepoint every refusal passes
    # through, so no present or future caller can forget it (V0-41).
    gap = classify_gap("refused", reason)
    if gap is not None:
        failure, closure, repair = gap
        record_gap(
            log_dir,
            ts=ts,
            run_id=run_id,
            task=task,
            cwd=cwd,
            attempted=attempted,
            failure=failure,
            detail=reason,
            closure=closure,
            repair=repair,
            source=REFUSED_KIND,
        )
    return recorded


def record_outcome(
    log_dir: Path,
    *,
    ts: str,
    run_id: str,
    task: str,
    cwd: str,
    harness: Harness,
    status: Status,
    reason: str,
    exit_code: int | None,
    artefact_bytes: int,
    diff_bytes: int,
    timed_out: bool,
    duration_s: float,
    command: Sequence[str],
) -> EventPayload:
    recorded = append(
        log_dir / f"{ts[:10]}.jsonl",
        _event(
            DISPATCH_OUTCOME_KIND,
            ts,
            {
                "run_id": run_id,
                "task": task,
                "cwd": cwd,
                "harness": harness.id,
                "family": harness.family,
                "pool": harness.pool,
                "status": status,
                "reason": reason,
                "exit_code": exit_code,
                "artefact_bytes": artefact_bytes,
                "diff_bytes": diff_bytes,
                "timed_out": timed_out,
                "duration_s": duration_s,
                "command": list(command),
            },
        ),
    )
    # A non-ok outcome is a capability gap the runner already measured: the harness was
    # asked and could not do it. Recorded at the same chokepoint so "exit 0, nothing
    # written" can never again be only a success-shaped log line (V0-41).
    gap = classify_gap(status, reason)
    if gap is not None:
        failure, closure, repair = gap
        record_gap(
            log_dir,
            ts=ts,
            run_id=run_id,
            task=task,
            cwd=cwd,
            attempted=harness.id,
            failure=failure,
            detail=reason,
            closure=closure,
            repair=repair,
            source=DISPATCH_OUTCOME_KIND,
        )
    return recorded


def record_fanout(
    log_dir: Path,
    *,
    ts: str,
    run_id: str,
    task: str,
    cwd: str,
    first: Harness,
    second: Harness,
    first_status: Status,
    second_status: Status,
    verdict: VerdictKind,
    first_run_id: str,
    second_run_id: str,
) -> EventPayload:
    contributors = [
        {
            "logical_identity": first.id,
            "evidence_class": f"family:{first.family}",
            "status": first_status,
            "run_id": first_run_id,
        },
        {
            "logical_identity": second.id,
            "evidence_class": f"family:{second.family}",
            "status": second_status,
            "run_id": second_run_id,
        },
    ]
    return append(
        log_dir / f"{ts[:10]}.jsonl",
        _event(
            FANOUT_KIND,
            ts,
            {
                "run_id": run_id,
                "task": task,
                "cwd": cwd,
                "status": verdict,
                "reason": (
                    "independent families answering the same task; "
                    "agreement is evidence, disagreement is the finding"
                ),
                "contributors": contributors,
                "first": first.id,
                "second": second.id,
            },
        ),
    )
